export default  {
    MAIN_ROUTE: "/*",
    AUTH_ROUTE: "/auth",
    ADMIN_ROUTE: "/admin",
    USER_PAGE_ROUTE: "/user",
    IMAGES_PAGE_ROUTE: "/images",
    DOCUMENTS_PAGE_ROUTE: "/documents",
    VIDEOS_PAGE_ROUTE: "/videos",
    MESSAGES_ROUTE: "/messages",
    CHAT_ROOM_ROUTE: "/chatroom",
    FRIENDS_ROUTE: "/user/friends",
    USER_OPTIONS_ROUTE: "/user/options",
    USER_BLACK_LIST_ROUTE: "/user/banned",
    USER_ARTICLES_NAVIGATION_ROUTE: "/user/articles",
    USER_ARTICLES_ROUTE: "/user/articles/:userId",
    GROUPS_ROUTE: "/groups",
    GROUP_ROUTE: "/group",
    GROUP_BLACK_LIST_ROUTE: "/group/banned",
    ARTICLE_ROUTE: "/article/:articleId",
    ARTICLE_PAGE_CREATE_ROUTE: "/article/create-page/:articleId",
    ARTICLE_PAGE_UPDATE_ROUTE: "/article/update-page/:articleId/:articlePageId",
    ARTICLE_UPDATE_ROUTE: "/article/update/:articleId",
    ARTICLE_PAGE_ROUTE: "/article/:articleId/:articlePageId",
    ARTICLE_CREATE_ROUTE: "/article/create",
    //используется при навигации на страницу статьи
    ARTICLE_NAVIGATION_ROUTE: "/article",
    ARTICLES_ROUTE: "/articles",
    POST_ROUTE: "/post",
    API_URL: "https://localhost:7021"
};